{
 "title": "BT KPIs",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "{\"find\": \"terms\", \"field\": \"key\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Defects Closed/ Week",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:204",
       "field": "closing_date",
       "id": "2",
       "settings": { "interval": "1w", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:202", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "project: $project AND resolution: \"Done\"",
     "timeField": "closing_date"
    }
   ]
  },
  {
   "title": "Blocked Defects",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:429",
       "field": "status",
       "id": "2",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:427",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "project: $project AND status: \"Waiting Info in Sprint\"",
     "timeField": "creation_date"
    }
   ]
  },
  {
   "title": "Quality/ Time",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:602",
       "fake": true,
       "id": "3",
       "query": "*",
       "settings": {
        "filters": [
         {
          "$$hashKey": "object:613",
          "label": "On Time With Rework",
          "query": "quality_time: \"ReviewedWithReworkOnTime\""
         },
         {
          "$$hashKey": "object:616",
          "label": "Not On Time With Rework",
          "query": "quality_time: \"ReviewedWithReworkNotOnTime\""
         },
         {
          "$$hashKey": "object:619",
          "label": "On Time With No Rework",
          "query": "quality_time: \"ReviewedWithoutReworkOnTime\""
         },
         {
          "$$hashKey": "object:622",
          "label": "Not On Time With No Rework",
          "query": "quality_time: \"ReviewedWithoutReworkNotOnTime\""
         }
        ]
       },
       "type": "filters"
      },
      {
       "$$hashKey": "object:459",
       "field": "closing_date",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:457", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "project: $project AND type: \"Story\" AND (!resolution: Duplicate) AND status: \"Closed\" AND (!labels: (\"QualityManagement\", \"Setup\"))",
     "timeField": "closing_date"
    }
   ]
  },
  {
   "title": "Epic Type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:884",
       "fake": true,
       "id": "3",
       "query": "*",
       "settings": {
        "filters": [
         {
          "$$hashKey": "object:918",
          "label": "Change Request",
          "query": "epic.type: \"Change Request\""
         },
         {
          "$$hashKey": "object:921",
          "label": "Defect",
          "query": "epic.type: \"Defect\""
         },
         {
          "$$hashKey": "object:924",
          "label": "Feature Request",
          "query": "epic.type: \"Feature Request\""
         },
         {
          "$$hashKey": "object:927",
          "label": "Finding",
          "query": "epic.type: \"Finding\""
         },
         {
          "$$hashKey": "object:930",
          "label": "Informal Item",
          "query": "epic.type: \"Informal Item\""
         },
         {
          "$$hashKey": "object:933",
          "label": "Issue",
          "query": "epic.type: \"Issue\""
         }
        ]
       },
       "type": "filters"
      },
      {
       "$$hashKey": "object:689",
       "field": "creation_date",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:687", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "project: $project AND type: \"Epic\" AND (!resolution: (\"Duplicate\", \"Rejected\")) AND (!labels: (\"QualityManagement\", \"Setup\"))",
     "timeField": "creation_date"
    }
   ]
  },
  {
   "title": "Defect Source",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1227",
       "fake": true,
       "id": "3",
       "query": "*",
       "settings": {
        "filters": [
         {
          "$$hashKey": "object:1238",
          "label": "External",
          "query": "defect_source: \"External\""
         },
         {
          "$$hashKey": "object:1241",
          "label": "Internal",
          "query": "defect_source: \"Internal\""
         },
         {
          "$$hashKey": "object:1244",
          "label": "Not Applicable",
          "query": "defect_source: \"Not Applicable\""
         }
        ]
       },
       "type": "filters"
      },
      {
       "$$hashKey": "object:1083",
       "field": "creation_date",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1081", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "project: $project AND type: \"Epic\" AND (!resolution: (\"Duplicate\", \"Rejected\")) AND (!labels: (\"QualityManagement\", \"Setup\"))",
     "timeField": "creation_date"
    }
   ]
  }
 ]
}